"""Add Producto model for inventory

Revision ID: 126c3f44915f
Revises: df7da2ad8a0b
Create Date: 2025-10-26 03:35:32.452531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126c3f44915f'
down_revision: Union[str, None] = 'df7da2ad8a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
