"""Initial migration - Vendedor model

Revision ID: 8a18800d8f3d
Revises: 
Create Date: 2025-10-26 02:59:57.827243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a18800d8f3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendedores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('red_social', sa.String(), nullable=True),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendedores_id'), 'vendedores', ['id'], unique=False)
    op.create_index(op.f('ix_vendedores_usuario'), 'vendedores', ['usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendedores_usuario'), table_name='vendedores')
    op.drop_index(op.f('ix_vendedores_id'), table_name='vendedores')
    op.drop_table('vendedores')
    # ### end Alembic commands ###
